### ISSUE TITLE
CustomPaint with Transparent background

### ISSUE THREAD

**Issue by Shvet** [igniti0n/draw_application#1]
Hello,
I am trying to overlay CustomPaint to another widget and for that i want ti make it tansparent so i can show another widget below and custom paint on top of it for editing. Can you share any comments to make it transparent? I tried adding color on canvas with transparent but didnt work.

**Comment by igniti0n** [comment]
Hello,

I put together a Stack like this, with the painter:

`return Stack(
          fit: StackFit.expand,
          children: [
            Positioned(
              left: 40,
              top: 40,
              child: Container(
                width: 400,
                height: 400,
                decoration: BoxDecoration(
                  color: Colors.blue,
                  shape: BoxShape.circle,
                ),
                child: TextButton(
                  style: ButtonStyle(
                    overlayColor: MaterialStateProperty.all(Colors.green),
                    foregroundColor: MaterialStateProperty.all(Colors.green),
                    fixedSize: MaterialStateProperty.all(
                      Size.fromHeight(400),
                    ),
                  ),
                  onPressed: () {},
                  child: Text(
                    "Hello",
                    style: TextStyle(fontSize: 48),
                  ),
                ),
              ),
            ),
            CustomPaint(
              foregroundPainter: AppPainter(),
            ),
          ],
        );`

Painter:

`@override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red
      ..strokeWidth = 80
      ..style = PaintingStyle.stroke;

    Rect rect = Offset.zero & size;
    canvas.saveLayer(rect, paint);

    final _rect = RRect.fromLTRBR(100, 100, 400, 400, Radius.zero);

    //canvas.drawRRect(_rect, paint);
    canvas.drawArc(
      Rect.fromLTWH(100, 100, 400, 400),
      0,
      3.14,
      false,
      paint..strokeCap = StrokeCap.round,
    );

    canvas.restore();
  }`


This draws me a container filled with cooler and a button underneath a custom paint that draws an arc, elements can be seen below.

Can you provide more detail if this doesn't work for you?  This draws the container and button inside it under the custom paint. 



It also worked for making custom dummy button and putting some painter over it, you can put multiple fo this buttons in a row for ex too:

`import 'package:flutter/material.dart';
import 'package:paint_app/domain/entities/drawing.dart';

import 'app_painter.dart';

class PainterButton extends StatelessWidget {
  const PainterButton({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 80,
      height: 80,
      child: Stack(
        fit: StackFit.expand,
        children: [
          Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: Colors.blue,
              shape: BoxShape.circle,
            ),
            child: TextButton(
              style: ButtonStyle(
                overlayColor: MaterialStateProperty.all(Colors.green),
                foregroundColor: MaterialStateProperty.all(Colors.green),
                fixedSize: MaterialStateProperty.all(
                  Size.fromHeight(80),
                ),
              ),
              onPressed: () {},
              child: Text(
                "Hello",
                style: TextStyle(fontSize: 48),
              ),
            ),
          ),
          CustomPaint(
            foregroundPainter: AppPainter(
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by Shvet** [comment]
This is how i have added customPainer, I have used same as you code for custom painter. 

```
child: Stack(
              alignment: Alignment.topCenter,
              fit: StackFit.expand,
              children: [
                Positioned.fill(
                  child: PdfView(
                    controller: _pdfController,
                    physics: ScrollPhysics(),
                    scrollDirection: Axis.vertical,
                    onDocumentError: (error) {},
                    onPageChanged: (pageNumber) {
                      currentPage = pageNumber;
                    },
                    backgroundDecoration: BoxDecoration(
                      color: isNightMode ? Colors.black : Colors.white,
                    ),
                    pageLoader: Center(
                      child: CircularProgressIndicator(),
                    ),
                    pageSnapping: false,
                  ),
                ),
                Positioned.fill(
                  child: Visibility(
                    visible: isDrawing,
                    child: GestureDetector(
                      onPanUpdate: (details) {
                        setState(() {
                          RenderBox renderBox =
                              context.findRenderObject() as RenderBox;
                          points.add(DrawingPoints(
                              points: renderBox
                                  .globalToLocal(details.globalPosition),
                              paint: Paint()
                                ..strokeCap = strokeCap
                                ..isAntiAlias = true
                                ..color = selectedColor.withOpacity(opacity)
                                ..strokeWidth = strokeWidth));
                        });
                      },
                      onPanStart: (details) {
                        setState(() {
                          RenderBox renderBox =
                              context.findRenderObject() as RenderBox;
                          points.add(DrawingPoints(
                              points: renderBox
                                  .globalToLocal(details.globalPosition),
                              paint: Paint()
                                ..strokeCap = strokeCap
                                ..isAntiAlias = true
                                ..color = selectedColor.withOpacity(opacity)
                                ..strokeWidth = strokeWidth));
                        });
                      },
                      onPanEnd: (details) {
                        setState(() {
                          points.add(null);
                        });
                      },
                      child: CustomPaint(
                        size: Size.infinite,
                        painter: DrawingPainter(
                          pointsList: points,
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
```

in Short i am trying to let user write on top of pdf like highlighting text or something and taking screenshot after that. If i use like above code custompaint is not being shown as a transparent. So i tried to make screenshot first and then add it to `CustomPaint ` by `drawImage` . 

As for your above solution i haven't tried yet, so let me check if it will work or not.

**Comment by igniti0n** [comment]
Hmmm...can you maybe share code on GitHub (just the PDF load and drawing part not the whole app off), try to put together similar setup I used some lib from pub.dev for PDF, the pdf did not load properly in this picture but I can draw on it as I wish

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-20 at 17 10 56](https://user-images.githubusercontent.com/59211351/130254547-4bb26159-ae14-434f-a9f7-c907e398e1ea.png)


And the code is like this (Drawin and gesture detector are for drawing, point is it is just in a stack, with custom paint having a child container, that is transparent, I am able to see all underneath):


`Stack(
          alignment: Alignment.topCenter,
          fit: StackFit.expand,
          children: [
            PDFScreen(
              path: path,
            ),
            RepaintBoundary(
              child: CustomPaint(
                isComplex: true,
                willChange: true,
                foregroundPainter: AppPainter(
                  Drawing(
                    canvasPaths: state.currentDrawing,
                  ),
                ),
                child: BlocListener<SettingsBloc, SettingsState>(
                  listener: (context, state) {
                    _currentPaintSettings = state.paintSettings;
                  },
                  child: GestureDetector(
                    onPanStart: (det) {
                      _newPath = CanvasPath(
                          paint: _paintFrom(_currentPaintSettings),
                          drawPoints: [
                            det.localPosition,
                          ]);
                      _newPath.movePathTo(
                          det.localPosition.dx, det.localPosition.dy);

                      _drawingBloc.add(StartDrawing(_newPath));
                    },
                    onPanUpdate: (det) => addPoint(
                      Offset(det.localPosition.dx, det.localPosition.dy),
                    ),
                    onPanEnd: (det) => addLastPoint(),
                    child: Container(
                      constraints: BoxConstraints(
                        maxHeight: _size.height,
                        maxWidth: _size.width,
                      ),
                      color: Colors.transparent,
                    ),
                  ),
                ),
              ),
            ),
          ],
        );`


Also RepaintBoundry will help you with performance, as drawing needs to be re-renderd many times while other things do not.
